name: Strategy test
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  probe:
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "strategy without matrix OK"
